require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'kiira' do
  config = use_native_modules!

  # App Permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "../node_modules/react-native-permissions/ios/Camera.podspec"
  pod 'Permission-Contacts', :path => "#{permissions_path}/Contacts.podspec"
  pod 'Permission-Microphone', :path => "#{permissions_path}/Microphone.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"

  # Twilio
  pod 'react-native-twilio-video-webrtc', path: '../node_modules/react-native-twilio-video-webrtc'

  use_react_native!(:path => config["reactNativePath"])

#   target 'kiiramobileTests' do
#     inherit! :complete
#     # Pods for testing
#   end

#   # Enables Flipper.
#   #
#   # Note that if you have use_frameworks! enabled, Flipper will not work and
#   # you should disable these next few lines.
#   use_flipper!
#   post_install do |installer|
#     flipper_post_install(installer)
#   end
# end

# target 'kiiramobile-tvOS' do
#   # Pods for kiiramobile-tvOS

#   target 'kiiramobile-tvOSTests' do
#     inherit! :search_paths
#     # Pods for testing
#   end
end
