export default {
    user: {
        acceptedTreatmentTerms: false,
        chats: '',
        consentAgreements: [],
        displayName: '',
        email: '',
        fcmToken: '',
        firstLogin: true,
        isActive: false,
        isOnline: false,
        prepaid: 0,
        organizationId: '',
        profileInfo: {
            dob: '',
            enrollment: '',
            ethnicity: {
                value: '',
                code: '',
            },
            firstName: '',
            foodSecure: '',
            gender: '',
            homeSecure: '',
            income: {
                code: '',
                value: '',
            },
            insurance: '',
            insurancePlan: '',
            lang: 'en',
            isActive: false,
            lastName: '',
            phoneNumber: '',
            profileImageUrl: '',
            pronouns: '',
            sexuality: {
                value: '',
                code: '',
            },
            state: {
                code: '',
                value: '',
            },
            zipcode: '',
        },
        subscription: {
            id: '',
        },
        customer: {
            id: '',
        },
        plan: {
            id: '',
        },
        referalCode: '',
        role: '',
        signUpDate: '',
        stripeCustomerToken: '',
        toUserId: '',
        uid: '',
        updatedAt: '',
        visits: 0,
    },
    expert: {
        calendarID: '',
        chatEnabled: false,
        clinicInfo: {
            address: '',
            city: '',
            hours: [],
            license: '',
            name: '',
            phoneNumber: '',
            state: {
                code: '',
                value: '',
            },
            zipcode: '',
        },
        credits: '',
        expertName: '',
        fcmToken: '',
        isActive: '',
        isOnline: '',
        profileInfo: {
            bio: '',
            city: '',
            dob: '',
            email: '',
            firstName: '',
            gender: '',
            languages: [],
            lastName: '',
            profileImageUrl: '',
            license: {
                states: [],
            },
            profession: {
                fullName: '',
                shortName: '',
                specialities: [],
            },
            pronouns: '',
            state: {
                code: '',
                value: '',
            },
        },
        rating: '',
        referalCode: '',
        role: '',
        toUserId: '',
        uid: '',
        userRating: [],
        id: '',
        videoEnabled: false,
    },
    agreements: {
        contract: '',
    },
};
